#import widgets (for buttons) GUI, and Core
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 1000)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mmlbl = QtWidgets.QLabel(self.centralwidget)
        self.mmlbl.setGeometry(QtCore.QRect(30, 20, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setItalic(False)
        self.mmlbl.setFont(font)
        self.mmlbl.setObjectName("mmlbl")
        self.Updates_button = QtWidgets.QPushButton(self.centralwidget)
        self.Updates_button.setGeometry(QtCore.QRect(20, 70, 181, 31))
        self.Updates_button.setAcceptDrops(False)
        self.Updates_button.setObjectName("Updates_button")
        self.fwlbutton = QtWidgets.QPushButton(self.centralwidget)
        self.fwlbutton.setGeometry(QtCore.QRect(20, 110, 181, 31))
        self.fwlbutton.setObjectName("fwlbutton")
        self.rmvprosoftbutton = QtWidgets.QPushButton(self.centralwidget)
        self.rmvprosoftbutton.setGeometry(QtCore.QRect(20, 150, 181, 31))
        self.rmvprosoftbutton.setObjectName("rmvprosoftbutton")
        self.auditbutton = QtWidgets.QPushButton(self.centralwidget)
        self.auditbutton.setGeometry(QtCore.QRect(20, 190, 181, 31))
        self.auditbutton.setObjectName("auditbutton")
        self.basicConfbutton = QtWidgets.QPushButton(self.centralwidget)
        self.basicConfbutton.setGeometry(QtCore.QRect(220, 190, 181, 31))
        self.basicConfbutton.setObjectName("basicConfbutton")
        self.UserGroupsButton = QtWidgets.QPushButton(self.centralwidget)
        self.UserGroupsButton.setGeometry(QtCore.QRect(220, 70, 181, 31))
        self.UserGroupsButton.setObjectName("UserGroupsButton")
        self.malrembutton = QtWidgets.QPushButton(self.centralwidget)
        self.malrembutton.setGeometry(QtCore.QRect(220, 150, 181, 31))
        self.malrembutton.setObjectName("malrembutton")
        self.servsetbutton = QtWidgets.QPushButton(self.centralwidget)
        self.servsetbutton.setGeometry(QtCore.QRect(220, 110, 181, 31))
        self.servsetbutton.setObjectName("servsetbutton")
        self.srchmedbutton = QtWidgets.QPushButton(self.centralwidget)
        self.srchmedbutton.setGeometry(QtCore.QRect(20, 230, 181, 31))
        self.srchmedbutton.setObjectName("srchmedbutton")
        self.quit_button = QtWidgets.QPushButton(self.centralwidget)
        self.quit_button.setGeometry(QtCore.QRect(300, 260, 81, 41))
        self.quit_button.setObjectName("quit_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 422, 18))
        self.menubar.setObjectName("menubar")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbout_Creator = QtWidgets.QAction(MainWindow)
        self.actionAbout_Creator.setObjectName("actionAbout_Creator")
        self.actionHow_To_Use = QtWidgets.QAction(MainWindow)
        self.actionHow_To_Use.setObjectName("actionHow_To_Use")
        self.menuAbout.addAction(self.actionAbout_Creator)
        self.menuAbout.addAction(self.actionHow_To_Use)
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    #what the button look like and do, what buttons are named
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        #app Title
        MainWindow.setWindowTitle(_translate("MainWindow", "GIS Data Review"))
        self.mmlbl.setText(_translate("MainWindow", "Main Menu"))
        self.Updates_button.setText(_translate("MainWindow", "SHP/GPX"))
        self.fwlbutton.setText(_translate("MainWindow", "KML/KMZ"))
        self.rmvprosoftbutton.setText(_translate("MainWindow", "Export to SHP"))
        self.auditbutton.setText(_translate("MainWindow", "Export to KMZ"))
        self.basicConfbutton.setText(_translate("MainWindow", "Basic Config"))
        self.UserGroupsButton.setText(_translate("MainWindow", "ArcOnline"))
        self.malrembutton.setText(_translate("MainWindow", "ArcPro"))
        self.servsetbutton.setText(_translate("MainWindow", "System Scan"))
        self.srchmedbutton.setText(_translate("MainWindow", "Update GDR"))
        self.quit_button.setText(_translate("MainWindow", "Quit"))
        self.menuAbout.setTitle(_translate("MainWindow", "Help"))
        self.actionAbout_Creator.setText(_translate("MainWindow", "About Creator"))
        self.actionHow_To_Use.setText(_translate("MainWindow", "How To Use"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    app.setStyle('Fusion')
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())